SHOW DATABASES;
-- DROP DATABASE ecommerce;

CREATE TABLE Dealers(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
	name VARCHAR( 60 ) NOT NULL,
	address VARCHAR( 200 ) NOT NULL,
	city VARCHAR( 60 ) NOT NULL,
	state VARCHAR( 60 ) NOT NULL
);

CREATE TABLE Categories(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
	name VARCHAR( 100 ) NOT NULL
);

CREATE TABLE Pieces(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
	name VARCHAR( 60 ) NOT NULL,
	price DECIMAL NOT NULL,
	color VARCHAR( 60 ) NOT NULL,
	
	category_id INT UNSIGNED NOT NULL,
	FOREIGN KEY( category_id ) REFERENCES Categories( id )
);

CREATE TABLE Purchases(
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
	quantity INT NOT NULL,
	date DATE NOT NULL,

	dealer_id INT UNSIGNED NOT NULL,
	piece_id INT UNSIGNED NOT NULL,
	
	FOREIGN KEY( dealer_id ) REFERENCES Dealers( id ),
	FOREIGN KEY( piece_id ) REFERENCES Pieces( id )
);





